name: 'Download a Build Artifact to Azure Blob Storage'
description: 'Download a build artifact that ca be used by subsequent workflow steps from Azure Blob Storage'
author: 'eavfw'
branding:
  icon: 'sunrise'
  color: 'orange'
inputs:
  connection-string:
    description: 'Connection string'
    required: true
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Directory containing files to upload'
    required: true

runs:
  using: "composite"
  steps:
     - name: Build Action
       run: docker build -t blob-storage-download-artifact:latest .
       shell: cmd
       working-directory: ${{ github.action_path }}
       if: runner.os == 'Windows'
     - name: Invoke Action
       run: docker run -e GITHUB_RUN_ID=${{ github.run_id }} -v ${{ inputs.path }}:/data  blob-storage-download-artifact:latest --name ${{ inputs.name }} --connection-string ${{ inputs.connection-string }} --path /data
       shell: cmd
       if: runner.os == 'Windows'
     
     - name: Build Action
       run: docker build -t blob-storage-download-artifact:latest .
       shell: bash
       working-directory: ${{ github.action_path }}
       if: runner.os == 'Linux'
     - name: Invoke Action
       run: docker run -e GITHUB_RUN_ID=${{ github.run_id }} -v ${{ inputs.path }}:/data  blob-storage-download-artifact:latest --name ${{ inputs.name }} --connection-string "${{ inputs.connection-string }}" --path /data
       shell: bash
       if: runner.os == 'Linux'

#    - run: dotnet run --project ${{ github.action_path }}/src/EAVFW.Extensions.GitHub.BlobStorageDownloadArtifact.csproj --name ${{ inputs.name }} --connection-string ${{ inputs.connection-string }} --path ${{ inputs.path }}
      #if: runner.os == 'Windows'
 